export default function CopyText() {
  return (
    <p className="text-justify">
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum nemo enim in ut pariatur eveniet, non quibusdam animi dicta soluta, officia asperiores dolorem expedita! Itaque vel aspernatur beatae eaque fuga cupiditate culpa dolorum iure! Modi architecto libero possimus, ut veniam harum itaque aliquid consequuntur recusandae quam fugit unde eligendi sequi ea labore temporibus eius deserunt quasi perspiciatis sapiente odit consequatur facere nulla. Beatae, quis et. Ut, accusamus fugiat incidunt, beatae quod rem, labore quam eius alias cupiditate corrupti sequi?
      
      Dolorum velit quo laudantium, nemo quia tempora fuga similique explicabo quisquam ratione sint in consectetur dolor iste totam id, vel quis amet, adipisci reprehenderit eveniet enim commodi! Labore laborum eius dignissimos fugit iste impedit. Magni, placeat minus?
      
      Obcaecati facilis, libero a vel iusto aspernatur accusantium?
      
      Nulla libero fuga natus, illum, numquam ad, aliquam error exercitationem debitis dolorum beatae eligendi nisi quos ea. Expedita consequatur accusamus consectetur reprehenderit cumque veritatis ipsum est ea, ullam ratione atque tenetur aspernatur unde quae ipsam tempora earum perspiciatis nulla sint minima facere, impedit numquam ex. Optio nesciunt sequi odit minus fugit, quibusdam itaque beatae deserunt, cum in et consequatur?
      
      Quae suscipit aliquam pariatur repellendus earum beatae. Quisquam repellendus mollitia, quae sint facilis corporis voluptatibus autem iure corrupti sed molestias omnis eaque eos adipisci dolorem iusto?
      
      Eius ea obcaecati adipisci doloremque quis perspiciatis nemo nobis velit eum dolorum nesciunt, aspernatur, earum blanditiis illo necessitatibus in molestias similique omnis rerum. Quis fugiat qui modi vel, cupiditate iusto error dolor accusamus, sit molestias itaque ratione deleniti possimus blanditiis facere aspernatur tempore reprehenderit similique minima voluptates beatae voluptas. Fuga similique sequi a commodi nesciunt quas officia, vero, debitis, suscipit repudiandae dolor. Consequatur officiis officia illo consectetur, id earum ipsam similique, laborum quidem placeat quae quos nobis tempora hic neque, quo explicabo excepturi fuga ipsa labore. Eaque est, fugit ullam dicta tempore quam assumenda! Praesentium doloremque esse autem accusantium, repudiandae inventore cupiditate totam, provident animi maxime consequuntur, alias magnam asperiores sapiente ex quas deserunt maiores reprehenderit. Magnam, accusantium numquam animi omnis blanditiis libero sunt qui maxime quas suscipit molestiae soluta voluptates consequatur voluptas perspiciatis odio iure. Nulla, accusamus, voluptas perferendis deserunt voluptatum nesciunt dicta sed ea a necessitatibus esse amet officiis. Voluptate ducimus consequuntur cum ullam corporis. Voluptas voluptatibus impedit nemo provident repudiandae architecto tempora ea minima, quisquam quis soluta. Molestias sed omnis tenetur similique perspiciatis maiores perferendis totam odit, non est ad aspernatur laboriosam porro minus libero vero vitae dolor atque inventore a praesentium quaerat ipsum minima. Recusandae, voluptate debitis! In, quod quae inventore porro ullam dolorem perferendis vero omnis tempora vel ducimus, libero provident deleniti. A provident suscipit aliquam error velit, modi repellat quod assumenda architecto maiores asperiores tempore ex impedit pariatur. Voluptatum totam, fugit nulla repudiandae dicta harum itaque amet deleniti doloribus, reiciendis ad, at quaerat vero necessitatibus iste. Est doloribus in a quibusdam quo et aliquid cum excepturi reiciendis omnis?
      
      Omnis harum perspiciatis praesentium saepe optio minima sit placeat corporis fugit amet ipsam laudantium enim facere ex voluptatibus aperiam est, quo rem. Quas in debitis nisi. Fugiat.
    </p>
  )
}